# Root directory
_DN_TOOLS=.tools
# DAM directory
_DN_DAM=.dam

__CORE_FILE=./${_DN_TOOLS}/${_DN_DAM}/core.Makefile

# Include core if present
ifneq ("$(wildcard $(__CORE_FILE))","")
  include $(__CORE_FILE)
endif

# # #
# # ‼️ DO NOT EDIT THIS FILE ‼️
# # #

do_install_dam_tool:
	@echo "Installing DAM tool...\n";
	@ wget -qO- "https://github.com/alecrabbit/dev-app-makefile/archive/refs/tags/0.0.19.tar.gz" \
      | tar -xz && shopt -s dotglob && cp -rv dev-app-makefile-0.0.19/* . \
      && shopt -u dotglob && rm -r dev-app-makefile-0.0.19 && ./install && make upgrade
